# permissions for end users to view blenderrenders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blenderrender-viewer-role
rules:
- apiGroups:
  - openshiftdemos.github.io
  resources:
  - blenderrenders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openshiftdemos.github.io
  resources:
  - blenderrenders/status
  verbs:
  - get
