apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: blender-render-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: BlenderRender is the Schema for the blenderrenders API
      displayName: Blender Render
      kind: BlenderRender
      name: blenderrenders.openshiftdemos.github.io
      version: v1alpha1
  description: This operator takes blend files as input and performs headless rendering
    within a kubernetes cluster.
  displayName: Blender Render Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - blender
  - render
  - headless
  links:
  - name: Blender Render Operator
    url: https://blender-render-operator.domain
  maturity: alpha
  provider:
    name: blender-operator
  version: 0.0.0
